# Generated by Django 3.0.3 on 2020-09-25 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shareRes', '0002_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='restaurant_content',
            field=models.CharField(max_length=100),
        ),
    ]
